# Feign
feign:
  compression:
    request:
      mime-types: "application/json"
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
integration:
  base:
    url: "localhost:8080"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/teacher

  rabbitmq:
    addresses: amqp://localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: exchange_activity_sender_request


server:
  port: 8082

# Logging
logging:
  level:
    org.springframework.cloud: 'INFO'
    com.schoolmanager: 'INFO'