# Feign
feign:
  compression:
    request:
      mime-types: "application/json"
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
integration:
  base:
    url: "localhost:8089"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/school

server:
  port: 8088


# Logging
logging:
  level:
    org.springframework.cloud: 'INFO'
    com.schoolmanager: 'INFO'
